export const FETCH_NOTES = 'FETCH_NOTES';
export const FETCH_NOTES_SUCESS = 'FETCH_NOTES_SUCESS';
export const FETCH_NOTES_FAILURE = 'FETCH_NOTES_FAILURE';

export const CREATE_NOTE = 'CREATE_NOTE';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const CREATE_NOTE_FAILURE = 'CREATE_NOTE_FAILURE';
